### ISSUE TITLE
SimpleRTK build fails for releases distributed as zipfiles due to missing git version details

### ISSUE THREAD

**Issue by djboersma** [RTKConsortium/RTK#152]
As the title says. I downloaded the 1.4 zip file and tried to build it, enabling a few more options than I actually need, in particular SimpleRTK. The build of RTK itself succeeds but SimpleRTK fails because in line 37-40 of `utilities/SimpleRTK/CMake/srtkSourceVersion.cmake` it tries to include the `srtkSourceVersionVars.cmake` file that does not yet exist (if the source had been checked out with git then that cmake file would be generated from the `srtkSourceVersionVars.cmake.in` source template file).

I guess there are several ways to solve this trivial issue. One way would be to add a pre-generated `srtSourceVersionVars.cmake` file to the release zip file.

For me this issue is not critical, because I do not actually need SimpleRTK for anything. I was just curious. After switching off SimpleRTK the installation of RTK version 1.4 succeeded.

**Comment by SimonRit** [comment]
Thanks for the report. The release zip are automatically generated by github so it's not so simple to do it (although a separate release branch with this file would do). But I think we won't fix that because we will soon remove SimpleRTK for another type of Python wrapping (which are the only ones that we have supported and have been used to my knowledge). I'll close your issue as soon as this is done.
Simon

**Comment by SimonRit** [comment]
With the recent release of RTK v2 and associated python packages, SimpleRTK is no longer maintained and I suggest to use the new packages.
