### ISSUE TITLE
How to install RTK v2.0.0 as a ITK module

### ISSUE THREAD

**Issue by lucysrausch** [RTKConsortium/RTK#250]
Hey,

I would like to get started with this promising project, however I'm a bit confused by the installation process documented in your wiki: http://wiki.openrtk.org/index.php/RTK_wiki_help

I assume the documentation is outdated, as it relies on providing RTK the path to the ITK binaries.
However, in the release note for v2.0.0 you state it is now possible and preferred to build RTK as a module of ITK.

Can you please provide me the correct way of setting up RTK for the latest version?

Thanks a lot,
Niklas

**Comment by codeling** [comment]
Here's a very quick intro how it worked for my project:

- Get ITK 5.0.0
- In CMake configuration, enable "Module_RTK".
- In your project's CMake configuration, instead of "FindPackage(RTK)", add "RTK" to the components in the "FindPackage(ITK...)" call, e.g. "FindPackage(ITK COMPONENTS RTK)".

If you use INCLUDE(${ITK_USE_FILE}), you afterwards should be able to access all RTK functionality.

**Comment by SimonRit** [comment]
Fixed by #254
