### ISSUE TITLE
GetArrayFromImage fails

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#301]
The following code
```
import numpy as np
import itk
from itk import RTK as rtk

#itk.GetImageFromArray(np.zeros([20,10,30]).astype(np.float32))
ImageType = itk.Image[itk.F,3]
srcdraw = rtk.ConstantImageSource[ImageType].New()
srcdraw.SetSize([20,10,30])
srcdraw.Update()
itk.GetArrayFromImage(srcdraw.GetOutput())
```
produces the error
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    itk.GetArrayFromImage(srcdraw.GetOutput())                  
  File "/home/srit/miniconda3/envs/test36/lib/python3.6/site-packages/itkExtras.py", line 257, in GetArrayFromImage
    return _GetArrayFromImage(image_or_filter, "GetArrayFromImage", keep_axes, update)
  File "/home/srit/miniconda3/envs/test36/lib/python3.6/site-packages/itkExtras.py", line 248, in _GetArrayFromImage
    raise RuntimeError("No suitable template parameter can be found.")
RuntimeError: No suitable template parameter can be found.
```
with the latest version produced by Azure pipelines. Uncommenting the commented line makes it work. The official RTK python package on pypi (v2.0.1) does not show this behavior. Any clue @LucasGandel ?

**Comment by LucasGandel** [comment]
Nice catch! I am not sure what changed as it was not required before but this is the way to go.
We need to make sure itk.PyBuffer is loaded before calling GetArrayFromImage, otherwise [itk.PyBuffer.keys()](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkExtras.py#L242) contains only the types defined by itkPyBufferRTK, but the ones from itkPyBuffer are missing, resulting in ["No suitable template parameter..."](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkExtras.py#L244) error.
In opposition, GetImageFromArray [loads ](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkExtras.py#L287)PyBuffer so this is why the subsequent calls to GetArrayFromImage succeed.
As you suggested, adding the dependency on ITKBridgeNumpy fixes the issue are all deps are [loaded ](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkBase.py#L67)before loading the RTK module.
I think you can integrate this. Thanks!
