### ISSUE TITLE
Missing RTKConfig.cmake/rtk-config.cmake in standalone build

### ISSUE THREAD

**Issue by codeling** [RTKConsortium/RTK#377]
When I do a standalone build of RTK with latest master (commit 019b327d2fd26d97e61b43c4cd6167e04807b573), I cannot use the libraries in the resulting build folder from any of my CMake projects (via `FIND_PACKAGE(RTK REQUIRED)`); CMake complains about not being able to find RTKConfig.cmake or rtk-config.cmake (and indeed these files are not generated).

Am I doing something wrong in how I reference the standalone RTK? Is there some option I need to enable for these files to be generated? Or is this just not an intended use case anymore, with the integration of RTK into ITK - i.e. can I only use the RTK included in ITK as a library?

**Comment by SimonRit** [comment]
Indeed, since the integration as a submodule of ITK, you need to proceed as shown in the [first reconstruction example](https://github.com/SimonRit/RTK/blob/master/examples/FirstReconstruction/CMakeLists.txt#L7). You therefore don't need RTKConfig.cmake. That should also be true for a standalone RTK which still depends on ITK and modifies the ITK config accordingly as far as I understand..
