### ISSUE TITLE
rtkVarianTest is failing occasionally on MacOS / clang

### ISSUE THREAD

**Issue by SimonRit** [RTKConsortium/RTK#430]
The error manifests with `itkTestDriver: Process exception: Segmentation fault`, see e.g. https://my.cdash.org/viewTest.php?onlyfailed&buildid=2059619. The problem also occurs on github actions now, see e.g. #429. The crash only occurs occasionally, like a memory error, at the end of this [loop in rtkHndImageIO.cxx](https://github.com/SimonRit/RTK/blob/master/src/rtkHndImageIO.cxx#L228L258) with `std::cout`s. But like any memory problem, I can't be sure this is where the problem is...

@agravgaard

**Comment by agravgaard** [comment]
I was able to reproduce it by running with `-fsanitize`, but without that flag the test passed (5+ runs).

It lists both integer overflow and misaligned loads.

I tried casting the loaded values to `long long` before the arithmetic, which seems to remove half the problem.

Using memcpy instead of pointer casting also makes assignment make more sense to the compiler.

Finally the last problem seems to come from expat in ITK (integer overflow in hash) instead and not RTK.
This has been changed in upstream libexpat twice, [first in 2003](https://github.com/libexpat/libexpat/commit/b28869898a5bc870e620edce09a5e65b4d556ba7#diff-d1bcab18f24ba66b34aeb2e156f7fde58ef3de1a165514b0fccf0d04c26838f8L5331) and [then again in 2017](https://github.com/libexpat/libexpat/commit/3fcef5021abf2de7cb61c8716a4674017114b3a6#diff-d1bcab18f24ba66b34aeb2e156f7fde58ef3de1a165514b0fccf0d04c26838f8R6326)

I'm unsure about how the SetComponentType works and whether UINT is big enough.

**Comment by SimonRit** [comment]
Thanks a lot for looking into it. I'll test #439 and report back...

**Comment by SimonRit** [comment]
> Finally the last problem seems to come from expat in ITK (integer overflow in hash) instead and not RTK.
> This has been changed in upstream libexpat twice, [first in 2003](https://github.com/libexpat/libexpat/commit/b28869898a5bc870e620edce09a5e65b4d556ba7#diff-d1bcab18f24ba66b34aeb2e156f7fde58ef3de1a165514b0fccf0d04c26838f8L5331) and [then again in 2017](https://github.com/libexpat/libexpat/commit/3fcef5021abf2de7cb61c8716a4674017114b3a6#diff-d1bcab18f24ba66b34aeb2e156f7fde58ef3de1a165514b0fccf0d04c26838f8R6326)

Is ITK's libexpat up-to-date and, if not, should we propose an update? I'll check whether it would fix the problem (in case #439 does not fix it already).

**Comment by agravgaard** [comment]
It looks like it's mostly 18 years old, with a few fixes - an update may be a good idea.

**Comment by SimonRit** [comment]
What do you think @dzenanz @thewtex? If you're in favor of an update, any suggestion on how to proceed?

**Comment by dzenanz** [comment]
If you are willing to update it, I am totally in favor. I guess XML-based formats are not frequently used in ITK, so this issue hasn't cropped up before.
