### ISSUE TITLE
How can I get the original projection data via dicom image by calling rtk via python and reconstruct it again

### ISSUE THREAD

**Issue by zlbbme** [RTKConsortium/RTK#562]
Dear Code Contributors：
I have installed the RTK python library correctly!

I now have in my possession a dicom image of a patient obtained by CBCT scanning，But now I want to get its original projection data from this image and use this projection data for FDK reconstruction to get the image and make sure that the reconstructed image is consistent with the original image.

I have read some of the example.py  but get less information, if you could give some hints on the code I would be very grateful!

**Comment by SimonRit** [comment]
Not a code issue, use the [mailing list](https://www.creatis.insa-lyon.fr/mailman/listinfo/rtk-users) please.
The CBCT dcm image does not contain the raw data. you need to check whether you can access it on your scanner. What you can do is only reproject the current CBCT but that is not the same.
You can try rtkfdk for reconstructing the raw data if you get it but that is unlikely that the result will be consistent because each manufacturer has specific steps which are kept secret. The full procedure, in particular how to obtain the geometry file) will depend on the CBCT scanner.
